### ISSUE TITLE
Consider metabang-bind for destructuring?

### ISSUE THREAD

**Issue by mmontone** [ciel-lang/CIEL#11]
I've been programming in Javascript at work lately, and I see they do heavy use of destructuring.

That got me thinking why it was not like that in CL, and starting looking and found metabang-bind. I think it may be an underappreciated and underused library. I think it has the potential to make CL code more concise.

That's why I've forked it to improve it, but also to experiment a bit with it: https://github.com/mmontone/metabang-bind.

And I thought of CIEL, that already has alternatives for iteration (iterate) and pattern matching (trivia). Perhaps you could consider adding metabang-bind for binding/destructuring. 

I'm not sure. It is just an idea. It is up to you @vindarel .

See you!

**Comment by vindarel** [comment]
Indeed, thanks for the suggestion, I plan on adding such a macro. I am hesitating also with Rutils' `with`: https://github.com/vseloved/rutils/blob/master/docs/tutorial.md#rutilsbind

```
RTL-USER> (with ((a 1)  ; => plain let
                 (b c (values 2 3))  ; more than 2 variables => multiple-value-bind
                 ((d _ e &rest f) '(4 0 5 12 13 14 15))  ; a list => destructuring-bind
                 (((g :g) (h :h)) ? #h(:g 6 :h 7))   ; ? in 2nd position => generic-elt
                 ((i j) @ (make-foo :i 8 :j 9))  ; @ in 2nd position => smart-slot-value   
                 (((k k) (l l)) @ (make 'foo :k 10 :l 11)))
            (list* a b c d e g h i j k l f)))
(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15)

It also supports ignoring some of the bindings by putting _ instead of the variable name — like in the third clause (destructuring-bind).

It is extensible as it allows to add more variants that support custom clauses. This is defined in bind-dispatch that uses the first 2 arguments to decide, which operation to emit
```

If you have an opinion about the pros and cons, I'm all ears.

**Comment by mmontone** [comment]
Ah..I didn't know about rutilsbind. I'll have a look at it.

**Comment by mmontone** [comment]
This is what I see.

rutils.bind is very simple (here's all the code for it: https://github.com/vseloved/rutils/blob/master/core/bind.lisp), but could be powerful at the same time, with a more concise syntax. But less complete, with less built-ins out of the box (like access to plists and alists) (it is extensible though, so those could be implemented).

metabang-bind can be more verbose, but being verbose can be more explict and more readable? (I guess that's subjective, but rutils uses some symbols ? and @, metabang-bind uses explicit keyword indicators in general, like :plist, :values). Certainly less concise than rutils.bind, but with more built-ins, like plist and alist access, and destructuring in lambdas (lambda-bind).

Both are extensible.

I think I would take metabang-bind because of its verbosity (I see it as a plus for readability) and its completeness.

But that's just me. My 2 cents.

**Comment by vindarel** [comment]
All good points, thanks a lot for the review.

**Comment by vindarel** [comment]
I see you already made nice improvements, cool!

**Comment by mmontone** [comment]
You could also import `lambda-bind` that binds with `bind` in lambda parameters.

**Comment by mmontone** [comment]
```lisp
(mapcar (lambda-bind ((:plist x))
                    x)
    (list :x 22 :y 44))
```

Not sure how great it is, though. But it is there.
