### ISSUE TITLE
A dependency list?

### ISSUE THREAD

**Issue by glyh** [ciel-lang/CIEL#14]
Hello, I'm new to common lisp. When I try to install CIEL via quicklisp, seems like there are some dependencies not mentioned. Like cl-ppcre and swank, can you add the list to README?

**Comment by vindarel** [comment]
Hello, thanks for trying out CIEL. 

CIEL is not in Quicklisp, but we can load it after a clone in `~/quicklisp/local-projects/` with `ql:quickload`, I suppose you did that.

cl-ppcre is correctly listed in the dependencies of the .asd project file: https://github.com/ciel-lang/CIEL/blob/master/ciel.asd#L59

swank isn't, but I wonder why you have those issues.

You will also find the list of (direct) dependencies here: https://github.com/ciel-lang/CIEL/blob/master/docs/dependencies.md (https://ciel-lang.github.io/CIEL/#/dependencies)

**Comment by glyh** [comment]
Thanks! Closing this.
