### ISSUE TITLE
Please update FSet home page link

### ISSUE THREAD

**Issue by slburson** [ciel-lang/CIEL#50]
The FSet home page has moved to https://gitlab.common-lisp.net/fset/fset/-/wikis/home .  Please update `docs/dependencies.md`.

**Comment by vindarel** [comment]
Hi, done (although this page was auto-generated given the dependencies' ASDF data).

thanks.

**Comment by slburson** [comment]
Ooh!  Thanks for pointing that out -- I see that I neglected to updated that URL.  Fixed now.
