### ISSUE TITLE
core-image fails to build under MacOS with SBCL from MacPorts: "unrecognized LOCAL-NICKNAMES"

### ISSUE THREAD

**Issue by khinsen** [ciel-lang/CIEL#58]
Today I saw the announcement of v0.2, which motivated me to take a closer look.

I tried the core-image build under MacOS, using SBCL 2.4.4 from MacPorts. That ends with:

; caught ERROR:
;   (during macroexpansion of (UIOP/PACKAGE:DEFINE-PACKAGE FILE-FINDER ...))
;   unrecognized define-package keyword :LOCAL-NICKNAMES

After reading https://github.com/ciel-lang/CIEL/issues/23, this looks like an ASDF version issue. Not sure there is anything I can do about this (other than trying to submit an update to MacPorts, but that won't happen soon). Would be nice to have at least a list of minimal versions of everything in the installation instructions.

**Comment by vindarel** [comment]
> ASDF version issue

yes you can upgrade it with this one-liner:

    ( cd ~/common-lisp/ && wget https://asdf.common-lisp.dev/archives/asdf-3.3.5.tar.gz  && tar -xvf asdf-3.3.5.tar.gz && mv asdf-3.3.5 asdf )

I'll need to review the installation instructions and probably do some checks with some nice error messages.

**Comment by mikeivanov** [comment]
The same happens with brew-installed sbcl and ros. Upgrading asdf helps.

**Comment by khinsen** [comment]
Thanks @vindarel, with an updated ASDF I can build `ciel-core` just fine! So the only action required is to add a note about ASDF versions in the installation instructions.

**Comment by vindarel** [comment]
and done, I reshaped the installation instructions. Thanks.
