### ISSUE TITLE
macOS: make build -> CORESERVICES shared lib not found

### ISSUE THREAD

**Issue by mikeivanov** [ciel-lang/CIEL#61]
macOS 14.5 on M2 

$ make build
...
; Loading "ciel"
.............
To load "ciel/repl":
  Load 1 ASDF system:
    ciel/repl
; Loading "ciel/repl"
Registering built-in scripts in src/scripts/ …
  scripts: registering apipointer
  scripts: registering finder
  scripts: registering quicksearch
  scripts: registering simpleHTTPserver
  scripts: registering webapp-notify
  scripts: registering webapp

 ==> Running load hooks.
 ==> Gathering system information.
WARNING: Deploy does not currently support Darwin frameworks.
WARNING: Deploy does not currently support Darwin frameworks.
   -> Will load the following foreign libs on boot:
      (#<DEPLOY:LIBRARY READLINE> #<DEPLOY:LIBRARY LIBSSL>
       #<DEPLOY:LIBRARY LIBCRYPTO>)
 ==> Deploying files to /Users/mike/opt/CIEL/bin/
WARNING: redefining ASDF/UPGRADE:UPGRADE-ASDF in DEFUN
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD tid=259 "main thread" RUNNING
                                    {7005F00423}>:
  #<LIBRARY CORESERVICES> does not have a known shared library file path.

**Comment by vindarel** [comment]
Thanks for the report.

(I don't see "coreservices" in your error output.)

>  WARNING: Deploy does not currently support Darwin frameworks.

so, nothing to do yet, except contributing to Deploy? Well, there is *some* support: https://github.com/search?q=repo%3AShinmera%2Fdeploy+Darwin&type=code

```lisp 
(defun make-lib-pathname (name)
  (make-pathname :name (string name)
                 :type #+(and unix (not darwin)) "so"
                       #+darwin "dylib"
                       #+windows "dll"
                       #+nx "nro"
                       #-(or unix darwin windows nx)
                      (warn "Deploy does not currently support Darwin frameworks.")
```

>  does not have a known shared library file path.

looks related: https://github.com/Shinmera/deploy/issues/20 "#<LIBRARY LIBZ> does not have a known shared library file path"

---

Are you able to build the core image? It doesn't evolve Deploy.

    make image

**Comment by vindarel** [comment]
That being said, since the v0.2 of yesterday we don't rely any more on foreign libraries, except libreadline for the terminal REPL that we take for granted, we should be able to build the binary without Deploy, hence without this limitation.

**Comment by vindarel** [comment]
You could try this, build steps without Deploy: https://github.com/ciel-lang/CIEL/tree/build-without-deploy -> https://github.com/ciel-lang/CIEL/compare/master...build-without-deploy

**Comment by tpmoney** [comment]
> (I don't see "coreservices" in your error output.)

Looks like that might have been a bug when they copied the output, I see the same thing on an M1 macbook air and it should be between the `#` and `does not have...`:

```
WARNING: Deploy does not currently support Darwin frameworks.
WARNING: Deploy does not currently support Darwin frameworks.
   -> Will load the following foreign libs on boot:
      (#<DEPLOY:LIBRARY READLINE> #<DEPLOY:LIBRARY LIBSSL>
       #<DEPLOY:LIBRARY LIBCRYPTO>)
 ==> Deploying files to ${HOME}/quicklisp/local-projects/CIEL/bin/
WARNING: redefining ASDF/UPGRADE:UPGRADE-ASDF in DEFUN
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD tid=259 "main thread" RUNNING
                                    {70063206F3}>:
  #<LIBRARY CORESERVICES> does not have a known shared library file path.```

**Comment by vindarel** [comment]
hope you'll confirm @mikeivanov 

thanks @tpmoney I merge with your confirmation.

**Comment by mikeivanov** [comment]
Confirmed - working. Thanks.
