### ISSUE TITLE
Build: we might not need Deploy anymore (better for Darwin)

### ISSUE THREAD

**Issue by vindarel** [ciel-lang/CIEL#62]
Deploy helps in shipping a binary with foreign libraries. Since v0.2, we only rely on libreadline for the terminal REPL (not for the core image), and we take it for granted.

Deploy doesn't yet support Darwin frameworks:

>  WARNING: Deploy does not currently support Darwin frameworks.

see https://github.com/ciel-lang/CIEL/issues/61

**Comment by khinsen** [comment]
I just hit that error message. So I removed all references to `deploy` (in `Makefile`, `ciel.asd`, and `build-config.lisp`) and `make build` worked just fine. As does the resulting binary. I can do a pull request for that if you want, but I suspect it needs testing on other platforms.

**Comment by khinsen** [comment]
Oops, I just saw your commit along the same lines. Sorry for the noise!
